export const FETCH_TICKETS_PENDING = "FETCH_TICKETS_PENDING";
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_ERROR = "FETCH_TICKETS_ERROR";
export const SORT_TICKETS = "SORT_TICKETS";
export const ADD_TICKET = "ADD_TICKET";
export const SHOW_TICKET_ADD_MODAL = "SHOW_TICKET_ADD_MODAL";
export const CLOSE_TICKET_ADD_MODAL = "CLOSE_TICKET_ADD_MODAL";
