export const FETCH_TICKETS_PENDING = "FETCH_TICKETS_PENDING";
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_ERROR = "FETCH_TICKETS_ERROR";
export const SORT_TICKETS = "SORT_TICKETS";
export const ADD_TICKET = "ADD_TICKET";
